language: c
cache: ccache
compiler:
- gcc
- clang
os:
- linux
- osx
before_script: ccache -s || echo "CCache is not available."
script:
- rm -rf artifacts dest
- mkdir dest artifacts
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CPPFLAGS="-I/usr/local/opt/openssl/include
  -L/usr/local/opt/openssl/lib" ./configure --prefix="$PWD/dest" ; else ./configure --prefix="$PWD/dest" ; fi
- make -j2 all examples check && make -C tests run_local
- make install
- (cd dest && tar cvzf ../artifacts/librdkafka-X.tar.gz .)
sudo: false
deploy:
  provider: s3
  access_key_id:
    secure: "i7IAO5z6xYeVaOnFiJOz0wluH7CfGf39TiABQG/yQIIp53fRu+X94FBUS7xq2PziKV08ak8pNWWjenwRB/viPTGqFQDS/ypymhSGGQVTmhgG372ypODhqbnvzskMNe1wp+UFIl8LFVEaHMVPEwWVuYpXhWNMHGrr4uSQhF+5r0Y="
  secret_access_key:
    secure: q7rWZkwQqyIFu3i32y/rJsKF1AJpwIqQe3AhBFEqjCz80mdEYysvcHBfl956EAAr4qbR3umIKbkhRwbBVyDGlMaraZiR7YFgAO+v0DRFeMiF5XFE3KHNIpCQHSKnzOiL65TpJHZIoB+6w0lAbBVzj87MBN0axAeArHKiO1y8Eec=
  bucket: librdkafka-ci-packages
  skip_cleanup: true
  local-dir: artifacts
  upload-dir: travis-${TRAVIS_COMMIT}-${TRAVIS_BUILD_ID}
  on:
    repo: edenhill/librdkafka
    branch: ci-s3-test
